### ISSUE TITLE
pomm.el does not trigger a notification

### ISSUE THREAD

**Issue by elia-blue** [SqrtMinusOne/pomm.el#11]
I'm trying to get notifications for break/start work from pomm.el, but for some reason I cannot find the corrent configuration.

Configuration of `pomm.el`:
```
(use-package pomm
    :commands (pomm pomm-third-time)
    :config
    (pomm-mode-line-mode)
```

Configuration of `alert.el`:
```
(use-package alert
    :config
    (setq alert-default-style "notifier")
    )
```

I know for a fact that the alert configuration works, because I get notifications for Org Mode tasks.

Does someone know what I'm missing?

**Comment by SqrtMinusOne** [comment]
Unlike `pomm.el`, Org uses the built-in `notifications.el` instead of `alert.el` because `alert.el` is not a part of GNU Emacs.

I guess the problem is that your `alert-default-style` is set to something you system doesn't support. You can check by evaluating something like:
```lisp
(alert "Foo")
```
If the notification doesn't show up, check the list of available styles here: https://github.com/jwiegley/alert/tree/master#builtin-alert-styles

And find one that works for you. `'notifications` will probably work.

**Comment by SqrtMinusOne** [comment]
Ahh, I haven't noticed.

The value of `alert-default-style` should be a symbol, not a string. So your config certainly won't work. If you want "notifier", try:
```elisp
(setq alert-default-style 'notifier)
```
