### ISSUE TITLE
How to read the csv timestamps in Libreoffice? 

### ISSUE THREAD

**Issue by maikol-solis** [SqrtMinusOne/pomm.el#3]
I ran some pomodoro sessions, setting  the `pomm-csv-history-file` variable. 

The timestamps in the file have the form 

```
timestamp
1636221045
1636221049
1636221055
1636221122
1636221129
1636222121
```

But if I convert them to date format I get 

```
timestamp
01/22/73
01/26/73
02/01/73
04/09/73
04/16/73
01/03/76
```

Which are wrong for me. 

Is there a way to export the timestamps into a standard way like `"%Y-%M-%d %H:%m:%s"`?

Thanks.

**Comment by SqrtMinusOne** [comment]
These are UNIX timestamps, that is the number of seconds since 1970-01-01. LibreOffice time is the number of days since 1899-12-30.

So you can use the following formula to convert one to another: `=A2/(60*60*24) + 25569`. Then select the column and Format > Cells > Number > Date should make the date look like what you expect.

But saving timestamps in a custom format should definitely be an option, I'll add it in the next version.

**Comment by maikol-solis** [comment]
Thanks! 

I'll be looking forward to seeing those new options. 

Best.

**Comment by SqrtMinusOne** [comment]
Added. Set `pomm-csv-history-file-timestamp-format` however you like, the format is the same as in [format-time-string](https://www.gnu.org/software/emacs/manual/html_node/elisp/Time-Parsing.html).

I've left the default value as "%s" to be backwards-compatible, the format you mentioned should look like "%Y-%m-%d %H:%M:%S"

**Comment by maikol-solis** [comment]
Thanks!

**Comment by SqrtMinusOne** [comment]
Feel free to reopen if anything about this part goes wrong.
